main: su.nightexpress.coinsengine.CoinsEnginePlugin
version: '${project.version}'
name: CoinsEngine
author: NightExpress
desciption: Your best economy & custom currencies plugin.
depend: [ nightcore ]
softdepend:
  - Vault
  - PlaceholderAPI
  - PlayerPoints
  - DeluxeCoinflip
load: STARTUP
api-version: 1.18